apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  containers:
  - env:
    - name: MYSQL_DATABASE
      value: coffeebreak
    - name: MYSQL_ROOT_PASSWORD
      value: logmigpa
    image: mysql
    name: database
    resources: {}
  restartPolicy: OnFailure
status: {}
