apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "my-backendconfig"}'
  name: heimdall
  labels:
    app: heimdall
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: heimdall
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 3
  selector:
    matchLabels:
      app: heimdall # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: heimdall # has to match .spec.selector.matchLabels
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: coffeebreak
        - name: MYSQL_HOST
          value: "10.40.1.57"
        - name: MYSQL_PASSWORD
          value: logmigpa
        - name: MYSQL_USER
          value: root
        - name: ROOM_REPOSITORY
          value: https://federicoshytte.dk
        - name: USER_REPOSITORY
          value: https://federicoshytte.dk
        - name: REDIS_HOST
          value: "redis-master.default.svc"
        name: heimdall
        image: frederikbroth/cheimdall:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 100m
