apiVersion: v1
kind: Service
metadata:
  name: odin
  labels:
    app: odin
spec:
  type: NodePort
  ports:
  - port: 3020
    targetPort: 3020
  selector:
    app: odin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odin
  labels:
    app: odin
spec:
  selector:
    matchLabels:
      app: odin # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: odin # has to match .spec.selector.matchLabels
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: coffeebreak
        - name: MYSQL_HOST
          value: "10.40.1.57"
        - name: MYSQL_PASSWORD
          value: logmigpa
        - name: MYSQL_USER
          value: root
        name: user-repository
        image: frederikbroth/codin:latest
        ports:
        - containerPort: 3020
