apiVersion: v1
kind: Service
metadata:
  name: room-repository
  labels:
    app: room-repository
spec:
  type: NodePort
  ports:
  - port: 3011
    targetPort: 3011
  selector:
    app: room-repository
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-repository
  labels:
    app: room-repository
spec:
  selector:
    matchLabels:
      app: room-repository # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: room-repository # has to match .spec.selector.matchLabels
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: coffeebreak
        - name: MYSQL_HOST
          value: "10.40.1.57"
        - name: MYSQL_PASSWORD
          value: logmigpa
        - name: MYSQL_USER
          value: root
        name: room-repository
        image: frederikbroth/croomrepo:latest
        ports:
        - containerPort: 3011
