version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    image: lomztein/gcp-e22-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend-service

  backend-service:
    build: ./Backend
    image: lomztein/gcp-e22-backend:latest
    depends_on:
      - cache
      - mongo
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb://root:example@mongo:27017/?authMechanism=DEFAULT
      - MONGO_DB_NAME=gcp
      - REDIS_URI=cache:6379

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

  mongo:
    build: ./mongo
    image: lomztein/gcp-e22-mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  cache:
    driver: local