version: "3.9"  # optional since v1.27.0
services:
  server:
    build: .
    ports:
      - "8000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://lomzie:logmigpa@gcproject.y6ogq4t.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=gcproject
      - REDIS_URI=rediss://default:AVNS_haw2bGZ-5pgzOPMoyDr@redis-2849f33-lomztein4-10de.aivencloud.com:21831
      