apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: frontend # has to match .spec.selector.matchLabels
    spec:
      containers:
      - env:
        - name: BACKEND_URL
          value: http://backend-service:3000
        - name: GOOGLE_MAPS_API
          value: AIzaSyAcVpW4sh_rsN6BNV-iFJAUh7brrlwO_kM
        name: frontend
        image: lomztein/gcp-E22-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 100m
